name: empowerhr_moblie
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.4
  equatable: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - assets/background.png
    - assets/LOGO-02.png
    - assets/forgotPasswordImg.png
    - assets/verifyImg.png
    - assets/change_new_password_IMG.png
    - assets/image.png
    - assets/QR_code.png
    - assets/icons/home_icon1.png
    - assets/icons/home_icon2.png
    - assets/icons/chat_icon1.png
    - assets/icons/chat_icon2.png
    - assets/icons/project_icon1.png
    - assets/icons/project_icon2.png
    - assets/icons/report_icon1.png
    - assets/icons/report_icon2.png
    - assets/icons/account_icon1.png
    - assets/icons/account_icon2.png
